coal-library/coal

include/hpp/fcl/collision_data.h
See https://github.com/stack-of-tasks/pinocchio/pull/319
=> Provide operator== for DistanceResult

src/intersect.cpp, test/CMakeLists.txt, test/test_fcl_math.cpp
The bug was introduced by the switch to Eigen.
=> Fix Intersect::buildTrianglePlane

include/hpp/fcl/collision_data.h, src/narrowphase/details.h, test/test_fcl_geometric_shapes.cpp
=> Simplify sphereTriangleIntersect

include/hpp/fcl/mesh_loader/assimp.h, src/CMakeLists.txt, src/mesh_loader/assimp.cpp
This fixes a bug encountered with DAE files with a graph structure.
It also removes duplicated vertices. This ought to be double checked on the benchmark at some point.
=> Fix loading of some meshes

.travis.yml, include/hpp/fcl/mesh_loader/assimp.h, src/BVH/BVH_model.cpp, src/mesh_loader/assimp.cpp, src/narrowphase/gjk.cpp, test/CMakeLists.txt, test/collision.cpp, test/geometric_shapes.cpp, test/obb.cpp, test/utility.cpp, test/utility.h
Fixes compilation on trusty (see CI of #76 ).
There is a failure on Mac which I do not understand...
=> Fix unit-tests and compilation

.travis.yml, include/hpp/fcl/mesh_loader/assimp.h, src/mesh_loader/assimp.cpp, travis_custom/custom_before_install_osx.sh
- Fixes merge conflicts
- update CI.
=> Merge devel into refactoring

src/BVH/BVH_model.cpp, src/traversal/traversal_recurse.cpp, test/frontlist.cpp, test/utility.cpp, test/utility.h, travis_custom/custom_before_install_osx.sh
=> Bug fix in propagateBVHFrontListCollisionRecurse + unit-tests

include/hpp/fcl/math/matrix_3f.h, include/hpp/fcl/math/vec_3f.h
Do not suggest another deprecated header as an alternative.
=> Update deprecation warning

CMakeLists.txt
=> [CMake] Boost::chrono in required for tests

include/hpp/fcl/shape/details/convex.hxx
There is also a trailing space in this file, but I somehow managed not to remove it in this commit ;)
=> add missing include

doc/python/doxygen_xml_parser.py, doc/python/xml_docstring.py, include/hpp/fcl/BVH/BVH_front.h, include/hpp/fcl/collision_data.h, python/CMakeLists.txt, python/distance.cc, src/narrowphase/details.h
Point on sphere wasn't correct.
This PR also adds support for latex formulas when generating python documentation.
=> Fix boxSphereDistance

python/collision.cc, test/python_unit/CMakeLists.txt, test/python_unit/api.py
=> [Python] Fix bindings of CollisionResult.

CMakeLists.txt, doc/Doxyfile.extra.in, doc/python/doxygen-boost.hh, doc/python/doxygen.hh, doc/python/doxygen_xml_parser.py, include/hpp/fcl/narrowphase/narrowphase.h, include/hpp/fcl/shape/geometric_shapes.h, python/collision-geometries.cc, python/collision.cc, python/math.cc, src/narrowphase/details.h, src/narrowphase/narrowphase.cpp, test/geometric_shapes.cpp
This provides:
- a fix of https://github.com/stack-of-tasks/pinocchio/issues/638#issuecomment-602716082
- set argument name in Python doc.
=> [Python] Doc and minor update + [C++] bugfix

CMakeLists.txt, include/hpp/fcl/narrowphase/narrowphase.h, package.xml, python/collision-geometries.cc, python/collision.cc, python/distance.cc, python/fcl.cc, python/math.cc, src/narrowphase/details.h
@jmirabel You've been merging your code while I was also doing some modifications. Hope the release of @nim65s is not already available.
This PR improves the code efficiency and also provides new way of sharing the memory between Eigen and Numpy.
=> Improce code efficiency + use shared memory between Numpy and Eigen

src/mesh_loader/assimp.cpp
=> Fix remove of HPP_FCL_USE_ASSIMP_UNIFIED_HEADER_NAMES

include/hpp/fcl/collision.h, include/hpp/fcl/collision_data.h, include/hpp/fcl/narrowphase/narrowphase.h, python/collision-geometries.cc, python/collision.cc, src/distance/capsule_capsule.cpp
=> Enable early stopping for GJK solver when computing contacts

python/collision-geometries.cc, python/collision.cc, python/distance.cc, python/fcl.cc, python/fcl.hh, python/gjk.cc, python/math.cc, python/octree.cc, python/version.cc
Hi,
This implement the same workaround as https://github.com/stack-of-tasks/eigenpy/pull/226
Also ref. https://github.com/stack-of-tasks/tsid/issues/128
=> Silence boost bind warnings from boost python

include/hpp/fcl/collision_data.h, src/collision_func_matrix.cpp, test/distance_lower_bound.cpp
=> Fix update of distanceLowerBound

.github/workflows/ros_ci.yml, CMakeLists.txt, include/hpp/fcl/BVH/BVH_model.h, include/hpp/fcl/collision_data.h, package.xml, test/hfields.cpp, test/serialization.cpp
WIP - modifications to prepare for a release. Also addressing some warnings along the way and turning others off
=> Preparing for ROS1 and ROS2 release

src/narrowphase/gjk.cpp
Removing comment about inflation (already set to 0 before the switch). See #259
=> Removing comment about inflation.

.github/workflows/ros_ci.yml, include/hpp/fcl/broadphase/broadphase_dynamic_AABB_tree.h, include/hpp/fcl/broadphase/broadphase_dynamic_AABB_tree_array.h, include/hpp/fcl/broadphase/detail/hierarchy_tree_array-inl.h, include/hpp/fcl/data_types.h, include/hpp/fcl/internal/traversal_node_hfield_shape.h, include/hpp/fcl/shape/details/convex.hxx, include/hpp/fcl/shape/geometric_shapes.h, python/version.cc, src/BVH/BVH_model.cpp, src/BVH/BVH_utility.cpp, src/broadphase/broadphase_dynamic_AABB_tree.cpp, src/broadphase/broadphase_dynamic_AABB_tree_array.cpp, src/intersect.cpp, src/narrowphase/gjk.cpp, src/shape/geometric_shapes.cpp, test/collision.cpp, test/distance.cpp, test/geometric_shapes.cpp, test/utility.cpp
Uses C++11 features which I expect will be default after #260 merges
Following this PR, the only warnings I see locally are from the Python-autodoc
=> Address some warnings

.github/workflows/ros_ci.yml, CMakeLists.txt, include/hpp/fcl/BVH/BVH_model.h, include/hpp/fcl/collision_data.h, package.xml, test/hfields.cpp, test/serialization.cpp
Ports #255 to master to create a patch release 1.8.1 prior to the C++11/FCL 2.0 push
=> Patch release 1.8.1

CMakeLists.txt
This new update allows to enforce the VERSION compatibility policy
=> Sync submodule cmake

src/shape/convex.cpp
Qhull does not automatically order triangles when it computes a convex hull.
This causes the following kind of visual issues when rendering `Convex<Triangle>`:
This is because the renderer uses the normal of the triangles to compute shadows; the normal direction is given by the order of the points in the triangle.
This PR reorders the triangles correctly, so that we visually have:
=> Reorder triangles when computing convex hulls

src/narrowphase/gjk.cpp
Some rounding may affect the precision.
=> Fix assert precision in GJK

cmake-modules/Findassimp.cmake
Related to discussions here https://github.com/conda-forge/assimp-feedstock/issues/45
Thanks @traversaro for the quick suggestion.
=> Fix findAssimp on Windows

python/broadphase/broadphase_collision_manager.hh
Closes https://github.com/humanoid-path-planner/hpp-fcl/issues/400
=> Add missing boost include

.github/workflows/macos-linux-conda.yml, .github/workflows/windows-conda-clang.yml, .github/workflows/windows-conda-v142.yml
=> Update minimal Python version 

include/hpp/fcl/collision_object.h, src/broadphase/broadphase_dynamic_AABB_tree.cpp, src/broadphase/broadphase_dynamic_AABB_tree_array.cpp, src/collision.cpp, src/distance.cpp
=> [CollisionObject] Provide helpers to get raw pointer of CollisionGeometry

package.xml
- Allow to use HPP_FCL_VERSION_AT_LEAST to test if new feature are aviable
=> Increment version to allow other project to test new feature

.pre-commit-config.yaml, doc/gjk.py
Fix linters failure in gitlab CI.
=> Fix linters failure.

CMakeLists.txt, README.md
- fix project org in CMake listfile
- minor language changes to README
=> Minor changes following transition to `coal`

CMakeLists.txt
Follows https://github.com/jrl-umi3218/jrl-cmakemodules/pull/736
=> CMake: update ament packaging
