include/hpp/fcl/collision_data.h

For the operator in Contact, i am not sure about the "o1 == other.o1 && o2 == other.o2 " part but i think that there is no need to compare the pointed value but to ensure that they point to the same object, and then compare the normal and position of the contact.

Provide operator == in CollisionResult, CostSource and Contact

---

include/hpp/fcl/math/vec_3fx.h

The "equal" function does not return true even in test cases that use the exact same vector as reference and "other". Therefore, I found it reasonable to modify the operator ==.

modify implementation of operator == in /include/hpp/fcl/math/vec_3fx.h

---

.travis.yml
src/BV/OBB.cpp

This reverts commit 31e52cc90748f2a2b80232682ec2214fb71f140d to allow compilation on 14.04 again.
But… It raises yet another issue about one test not passing on [clang on 14.04](https://travis-ci.org/nim65s/hpp-fcl/jobs/477862462):
```
13/14 Test #13: test_fcl_profiling ...............***Exception: Other  1.43 sec
```
I suggest to ignore this error, and just drop support for clang on 14.04.

Revert "[OBB] Simplify expression in obbDisjointAndLowerBoundDistance", fix #46

---

include/hpp/fcl/collision_data.h
test/benchmark.cpp
test/test_fcl_collision.cpp
test/test_fcl_distance.cpp
test/test_fcl_distance_lower_bound.cpp
test/test_fcl_frontlist.cpp
test/test_fcl_octree.cpp
test/test_fcl_profiling.cpp
test/test_fcl_utility.h

Added default constructor
Removed default argument to deprecated method to remove ambiguity (behavior remains the same thanks to mentioned default constructor)

using flag structure for argurments to collision requests

---

CMakeLists.txt
include/hpp/fcl/BV/BV.h
include/hpp/fcl/mesh_loader/loader.h
include/hpp/fcl/narrowphase/narrowphase.h
include/hpp/fcl/shape/geometric_shapes.h
include/hpp/fcl/traversal/traversal_node_bvh_shape.h
src/BVH/BVH_model.cpp
src/collision_func_matrix.cpp
src/distance_box_sphere.cpp
src/mesh_loader/loader.cpp
src/narrowphase/details.h
src/narrowphase/narrowphase.cpp
src/shape/geometric_shapes.cpp
test/test_fcl_bvh_models.cpp
test/test_fcl_geometric_shapes.cpp
test/test_fcl_geometric_shapes.py

hpp-fcl only supports queries between BVH using the same bounding volume type. The API change of MeshLoader specifies the BV type at construction of the loader rather than when calling the method load.

Update API of MeshLoader + fix Convex class

---

include/hpp/fcl/mesh_loader/assimp.h

This is for making the code compliant with new policy in C++17.

core: remove throw from function declarations

---

README.md
src/narrowphase/gjk.cpp

The failure was due to a NaN value appearing when checking whether the origin is enclosed.
I started [CI on gitlab](https://gepgitlab.laas.fr/humanoid-path-planner/hpp-fcl/pipelines/5447)

[GJK] Fix GJK::encloseOrigin (fixes unit-tests)

---

CMakeLists.txt

Hi,
On some systems, we don't have `OCTOMAP_INCLUDE_DIRS` & `OCTOMAP_LIBRARY_DIRS` but `OCTOMAP_INCLUDEDIR` & `OCTOMAP_LIBDIR`, and therefore we get:
```
-- Checking for module 'octomap >= 1.6'
--   Found octomap , version 1.9.0
-- Pkg-config module octomap v1.9.0 has been detected with success.
-- FCL does not use Octomap
```

[CMake] fix octomap detection

---

include/hpp/fcl/mesh_loader/assimp.h

There is a compilation due to recent versions of assimp. This PR fixes it temporarly.
The current PR on the offical assimp repository with the fix is here: https://github.com/assimp/assimp/pull/2758

assimp: fix issue with recent version of assimp

---

python/CMakeLists.txt
python/fcl.cc
python/fcl.hh
python/version.cc

Updates the cmake module so that `HPP_VERSION_AT_LEAST` and `HPP_VERSION_AT_MOST` are automatically inserted in the `config` header.
Exposes version-related macros in Python as attributes and wrapper functions

Add version support

---

.gitignore
include/hpp/fcl/collision_object.h
include/hpp/fcl/shape/geometric_shapes.h
test/python_unit/geometric_shapes.py
test/python_unit/test_case.py

`computeVolume()`, `computeCoM()` and `computeMomentofInertia()` had bugs, one of them really stupid concerning the volume of the sphere.
I fixed them and tested them in Python.
I suspect there is still a bug in the capsule inertia, which is why I have commented that part of the unit test, but I do not have time for that now

[geometric_shape] Fix radius, CoM and inertia computation + Python unit tests

---

python/math.cc

It seems it has been removed. Fix issue https://github.com/stack-of-tasks/pinocchio/issues/1136

Add missing constructor for Transform3f

---

doc/python/xml_docstring.py
package.xml

This also bump the version in the package.xml.
I set it to the next release number because I think the devel branch should have a version number higher that the last release (except when they match, if course). On the practical aspect, this allows you to use stuff like `#ifdef HPP_FCL_VERSION_AT_LEAST(current devel version)` which will work with the next release.
Of course, we don't know yet whether next release will be 1.4.5 or 1.5 of 2.0 and we can adjust it upon release.

Fix Python 3 doc generation

---

include/hpp/fcl/collision.h
include/hpp/fcl/collision_data.h
include/hpp/fcl/distance.h
python/collision.cc
python/distance.cc
src/collision.cpp
src/distance.cpp
src/distance/capsule_capsule.cpp

This is a draft to open discussions on removing the overhead introduced by hpp-fcl design.
The following benchmark for capsule-capsule distance shows that a hpp-fcl design introduces about 12ns per call, which is about 23% of the current cost. The attempt to remove this cost proposed here makes the overhead drop to 2ns, so less than 5%.
**NOTE** this figures should be taken with care.
```c++
#include <hpp/fcl/shape/geometric_shapes.h>
#include <hpp/fcl/distance.h>
#include "../src/distance_func_matrix.h"
#include "utility.h"
#include <iostream>
#include <chrono>
template<typename TimeT = std::chrono::milliseconds>
struct measure
{
template<typename F, typename ...Args>
static typename TimeT::rep execution(F&& func, Args&&... args)
{
auto start = std::chrono::steady_clock::now(); …
```

Add DistanceFunctor

---

include/hpp/fcl/internal/traversal_node_base.h

enable_statistics was duplicated in derived class CollisionTraversalNodeBase.

[TraversalNodeBase] Remove duplicate member in derived class.

---

src/BV/OBB.cpp
test/obb.cpp

The register keyword leads to a compile error for C++ standards newer
than or equal to C++17.

Remove register keyword to fix #220

---

include/hpp/fcl/serialization/eigen.h

hpp-fcl v1.7.3 doesn't compile on the standard default configuration on
ArchLinux (GCC 11.1.0, Eigen 3.3.9, Boost 1.75.0) and on
Fedora 34 (GCC 11.1.1, Eigen 3.3.9, Boost 1.75.0), with the following
error message:
```
In file included from /usr/include/eigen3/Eigen/Core:368,
from ./hpp-fcl-1.7.3/include/hpp/fcl/data_types.h:41,
from ./hpp-fcl-1.7.3/include/hpp/fcl/collision.h:43,
from ./hpp-fcl-1.7.3/test/serialization.cpp:40:
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h: In instantiation of 'struct Eigen::internal::accessors_level':
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:109:58:   required by substitution of 'template class SPT> void boost::serialization::load(Archive&, SPT&, unsigned int) [with Archive = boost::archive::text_iarchive; SPT = ]' …
```

workaround GCC >= 7 / C++17 / boost::serialization / Eigen bug

---

test/collision.cpp

fix for Boost 1.76.0:
```
/src/hpp-fcl/test/collision.cpp:228:9: error: no template named 'vector' in namespace 'boost::mpl'; did you mean 'boost::container::vector'?
typedef boost::mpl::vector<OBB, RSS, KDOP<24>, KDOP<18>, KDOP<16>, kIOS, OBBRSS> BVs_t;
^~~~~~~~~~~~~~~~~~
boost::container::vector
/usr/local/include/boost/container/container_fwd.hpp:104:7: note: 'boost::container::vector' declared here
class vector;
^
/src/hpp-fcl/test/collision.cpp:228:21: error: too many template arguments for class template 'vector'
typedef boost::mpl::vector<OBB, RSS, KDOP<24>, KDOP<18>, KDOP<16>, kIOS, OBBRSS> BVs_t;
^                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/container/container_fwd.hpp:104:7: note: template is declared here
class vector;
^
```

[Tests] add missing include

---

CMakeLists.txt
src/CMakeLists.txt

Hi,
As discussed in #201, I'm activating Qhull on robotpkg. 
Doing so, I noticed that some distributions are already providing qhullcpp, so in that case there is no need to build it. This PR implement this case.
I also checked in other cases, where Qhull is installed but without qhullcpp, that the configuration provided by @jmirabel works well.

[CMake] use system Qhull if available

---

include/hpp/fcl/collision_object.h

The previous cgeom_const is not required.

Simplify CollisionObject by removing cgeom_const

---

include/hpp/fcl/collision_data.h
include/hpp/fcl/doc.hh
src/collision.cpp

This implements https://github.com/humanoid-path-planner/hpp-fcl/issues/269.

[ComputeCollision] Return no collision if security_margin is set to -inf

---

test/CMakeLists.txt

Hi,
This fix a very long standing bug, where unit tests would randomly segfault on exit, eg. [in CI](https://gitlab.laas.fr/humanoid-path-planner/hpp-fcl/-/jobs/141152):
```
14/19 Test #17: gjk ..............................Child aborted***Exception:   0.16 sec
Running 3 test cases...
nCol / nTotal = 2840 / 10000
nDiff = 0
Total / average time gjk: 6652, 6.652e-07s
-- Collisions -------------------------
Total / average time gjk: 1950, 6.8662e-07s
-- No collisions -------------------------
Total / average time gjk: 4702, 6.56704e-07s
*** No errors detected
malloc_consolidate(): invalid chunk size
```
This hit in many of our projects, but only on Debian, so we have just been ignoring most Debian CI job failures until now.
But this time, I noticed exactly the same issue on Arch, where 19 …

tests: remove link to boost unit test framework

---

include/hpp/fcl/broadphase/detail/simple_hash_table-inl.h
include/hpp/fcl/shape/geometric_shapes.h
package.xml
python/broadphase/broadphase_callbacks.hh
python/broadphase/broadphase_collision_manager.hh

This PR should get us to zero warnings with gcc and clang.
Once https://github.com/ros/rosdistro/pull/32683 is merged, we can uncomment the new dependency on pylatexenc in the package.xml and fix the unstable builds on the buildfarm (to remove the multi-line comment warnings and get nicer Python documentation strings in the bindings).

Zero warnings

---

package.xml

The key was merged, but won't be available during buildfarm builds - can be used for CI though :-)

Activate python3-pylatexenc dependency

---

package.xml

Builds are failing. Turns out these keys are available for developer machines but not for CI/buildfarm

Comment pylatexenc again since it's not available on the buildfarm

---

src/collision_func_matrix.cpp
src/distance_func_matrix.cpp

This is to resolve #293 .
When I added ellipsoids, I forgot to add them to the distance/collision matrix...
I will deal with Ellipsoids-Plane/Halfspace tomorrow.

Ellipsoids in collision & distance matrices

---

include/hpp/fcl/collision_data.h
include/hpp/fcl/data_types.h
include/hpp/fcl/narrowphase/gjk.h
include/hpp/fcl/narrowphase/narrowphase.h
python/gjk.cc
src/collision.cpp
src/collision_func_matrix.cpp
src/distance.cpp
src/distance_func_matrix.cpp
src/narrowphase/gjk.cpp
test/CMakeLists.txt
test/gjk.cpp
test/nesterov_gjk.cpp
test/utility.cpp
test/utility.h

This PR implements a Nesterov acceleration for the GJK algorithm. 
In `gjk.cpp`, we simply replace the direction used to compute support points from `ray` to `dir`, where `dir` is obtained using the Nesterov scheme. An enum allows to switch from `Default` GJK to `NesterovAcceleration` GJK.
The python bindings are modified accordingly.
In a following PR I will put a link to the corresponding paper.

Feature: Nesterov acceleration for GJK

---

include/hpp/fcl/collision_data.h
include/hpp/fcl/data_types.h
include/hpp/fcl/narrowphase/gjk.h
include/hpp/fcl/narrowphase/narrowphase.h
python/gjk.cc
src/collision.cpp
src/collision_func_matrix.cpp
src/distance.cpp
src/distance_func_matrix.cpp
src/narrowphase/gjk.cpp
test/CMakeLists.txt
test/gjk_convergence_criterion.cpp
test/nesterov_gjk.cpp

This PR adds the following:
- 2 more convergence criterions in addition to the default hppfcl criterion, in `GJK`. These provide different guarantees on the distance between the solution found by GJK and the optimal solution (the projection of the origin onto the Minkowski difference). Currently, hppfcl is using the criterion from the 1999 Van den Bergen [paper](http://www.dtecta.com/papers/jgt98convex.pdf). This PR adds the frank-wolf duality gap (used in the original GJK paper) as well as a mix between VDB and the duality-gap.
- exposing them to the collision/distance api, and to python
- tests for these criterions

Feature: adding convergence criterions for GJK algorithm

---

include/hpp/fcl/internal/traversal_node_bvh_shape.h
include/hpp/fcl/internal/traversal_node_bvhs.h
include/hpp/fcl/internal/traversal_node_hfield_shape.h
src/BV/OBB.cpp
src/BV/RSS.cpp
src/BV/kIOS.cpp

According to the definition of overlap, R0,T0 expressed the placement of the BV b1 and b2 is at the identity.
Consequently, we need either to transfert b1 to the origin or to express b2 in the frame of b1, defined by (R0,T0).

Fix incoherent overlap

---

python/octree.cc

Add `shared_ptr<OcTree>`, otherwise there will be `No to_python (by-value) converter found for C++ type` error for python binding `makeOcTree`

Expose shared_ptr<OcTree>

---

test/gjk_convergence_criterion.cpp

We are setting but never verifying the status in the test

test/gjk_convergence_criterion: Add check on GJK::Status

---

.github/workflows/conda/conda-env.yml
CMakeLists.txt

This will have to wait for eigenpy 2.7.10 to be available everywhere before the CI can succeed.

 CMake: update to eigenpy 2.7.10

---

.github/workflows/ros_ci.yml

Remove CI for EOL distro Galactic. This is likely to have caused the CI failures in #363

[CI] Remove EOL Galactic

---

.github/workflows/macos-linux-conda.yml

In this PR, we add options for the macos/linux build on Conda, similar to what was done [here](https://github.com/stack-of-tasks/eigenpy/blob/e9ba801d6563ce7a7aecaf9ca37eea54f5073714/.github/workflows/macos-linux-conda.yml) after [this PR](https://github.com/stack-of-tasks/eigenpy/pull/336/files).
The added build options are:
* compiling with the CMake `Debug` build type
* compiling with the `-mavx2` flag

CI : add build options (Debug, AVX2)

---

test/serialization.cpp

to fix cases where `export TMP=/build` would cause
> unknown location(0): fatal error: in "test_aabb": boost::archive::archive_exception: output stream error

tests: use boost::filesystem

---

CITATION.bib
CITATION.cff
include/hpp/fcl/BVH/BVH_model.h
include/hpp/fcl/internal/tools.h
src/BV/AABB.cpp
src/BV/OBB.cpp
test/obb.cpp

Add citations

---

.github/workflows/ros_ci.yml
include/hpp/fcl/BVH/BVH_model.h
include/hpp/fcl/internal/traversal_node_hfield_shape.h
include/hpp/fcl/internal/traversal_node_octree.h
include/hpp/fcl/internal/traversal_node_setup.h
include/hpp/fcl/serialization/BVH_model.h
include/hpp/fcl/serialization/convex.h
include/hpp/fcl/shape/convex.h
include/hpp/fcl/shape/details/convex.hxx
include/hpp/fcl/shape/geometric_shapes.h
python/collision-geometries.cc
src/BVH/BVH_model.cpp
src/BVH/BVH_utility.cpp
src/narrowphase/details.h
src/narrowphase/gjk.cpp
src/shape/convex.cpp
src/shape/geometric_shapes.cpp
src/shape/geometric_shapes_utility.cpp
test/convex.cpp
test/normal_and_nearest_points.cpp
test/utility.cpp

Related to #450.
Since we remove the concept of `own_storage` to use `std::shared_ptr` instead of raw pointers, this PR introduces a breaking change in the API, when creating `Convex` objects from scratch:
```cpp
// previously:
Vec3f* pts = new Vec3f[n_vertices];
Triangle* tris = new Vec3f[n_tris];
bool own_storage = true;
// fill pts and tris...
// then call the `Convex` constructor:
Convex<Triangle> cvx(own_storage, points, n_vertices, tris, n_tris);
// now:
std::shared_ptr<Vec3f> pts(new Vec3f[n_vertices]);
std::shared_ptr<Triangle> tris(new Vec3f[n_tris]);
// fill pts and tris...
// then call the `Convex` constructor:
Convex<Triangle> cvx = convexHull(points, n_vertices, tris, n_tris);
```

Convex and BVHModel: moving from raw to std::shared_ptr

---

include/hpp/fcl/BVH/BVH_model.h
include/hpp/fcl/data_types.h
include/hpp/fcl/internal/traversal_node_hfield_shape.h
include/hpp/fcl/internal/traversal_node_octree.h
include/hpp/fcl/internal/traversal_node_setup.h
include/hpp/fcl/serialization/BVH_model.h
include/hpp/fcl/serialization/convex.h
include/hpp/fcl/shape/convex.h
include/hpp/fcl/shape/details/convex.hxx
include/hpp/fcl/shape/geometric_shapes.h
python/collision-geometries.cc
src/BVH/BVH_model.cpp
src/BVH/BVH_utility.cpp
src/narrowphase/details.h
src/narrowphase/gjk.cpp
src/shape/convex.cpp
src/shape/geometric_shapes.cpp
src/shape/geometric_shapes_utility.cpp
test/convex.cpp
test/serialization.cpp
test/utility.cpp

A polytope can be seen as either a set of vertices or a set of planes (normals + offsets).
The double description is normals + offsets.
In GJK/EPA we only use the vertices of polytopes. However, for computing normals/witness points, having the double description may be usefull in the future.

Adding mesh double description

---

src/shape/geometric_shapes.cpp
test/convex.cpp

Previously, the pointers in `neighbors` were not pointing to the data stored in `nneighbors_` but to `other.nneighbors_`.
If `other.nneighbors_` is destroyed then the neighbors point to deleted data. This PR fixes that.

[ConvexBase] Fix neighbor copy in copy constructor.

---

include/hpp/fcl/broadphase/detail/morton.h

This fixes a compilation bug (missing types `uint32_t` and `uint64_t`) on my setup (Clang-15 from `apt` on Ubuntu, so not unusual), and in the abstract sense it's good to make sure we explicitly include the header which defines these [typedefs](https://en.cppreference.com/w/cpp/types/integer).

[broadphase/detail] explicitly include <cstdint> header in morton.h

---

include/hpp/fcl/narrowphase/gjk.h
python/gjk.cc
src/narrowphase/gjk.cpp
test/accelerated_gjk.cpp
test/gjk_convergence_criterion.cpp

This PR allows to retrieve the tolerance and iterations of both EPA and GJK algos.
Also, it counts the number of dot products during the calls to the support functions in GJK.
These metrics are useful when benchmarking collision detection.

Add metrics for gjk and epa

---

CHANGELOG.md
include/hpp/fcl/broadphase/default_broadphase_callbacks.h
python/broadphase/broadphase.cc

Broadphase clear collision data

---

CHANGELOG.md
include/hpp/fcl/broadphase/detail/hierarchy_tree-inl.h

In the case where only 2 shapes are used and one of them is a shape with infinite AABB (i.e Plane or Halfspace), `min_size` remains equal to +infinity in `HierarchyTree::bottomup` and `min_it1` and `min_it2` never got set, which was leading to a segfault when they are then dereferenced.

[broadphase] Initialize NodeVecIterator

---

CHANGELOG.md
CMakeLists.txt
include/hpp/fcl/collision_data.h
include/hpp/fcl/narrowphase/narrowphase.h
include/hpp/fcl/narrowphase/narrowphase_defaults.h
src/collision_node.cpp
src/narrowphase/gjk.cpp
test/CMakeLists.txt
test/collision_node_asserts.cpp
test/gjk_asserts.cpp

This PR is related to #380 where users are sometimes experiencing assertion errors in Debug mode.
This PR is related to one of these assertion triggers:
- When the user sets a tolerance for GJK and/or EPA that is too low, the support function may work with support directions that are almost zero, which is not suitable for GJK and EPA. In hppfcl, we have hard-coded assertion checks, and these checks make the assumption that GJK's tolerance is not below `1e-6`. This PR introduces default values for GJK and EPA and places a warning in Debug mode only for users going below this tolerance.
Side note: when working with the default GJK and EPA (default `1e-6` tolerance, default convergence criterion), it is precise up to the micro-meter, which is an **extremely** low tolerance. In practice, …

Setting default parameters for the narrowphase

---

CHANGELOG.md
include/hpp/fcl/broadphase/detail/interval_tree.h
include/hpp/fcl/broadphase/detail/interval_tree_node.h
src/broadphase/detail/interval_tree.cpp
src/broadphase/detail/interval_tree_node.cpp

nil is used as macro definition on recent APPLE platforms, as shown by this compilation error: 
```bash
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/MacTypes.h:92:19: note: expanded from macro 'nil'
#define nil nullptr
```

Fix compatibility with recent APPLE compilers

---

CHANGELOG.md
test/normal_and_nearest_points.cpp

Test: fix compilation error with Eigen 3.3.7

---

CHANGELOG.md
include/hpp/fcl/collision_data.h
include/hpp/fcl/data_types.h
include/hpp/fcl/fwd.hh
include/hpp/fcl/narrowphase/gjk.h
include/hpp/fcl/narrowphase/narrowphase.h
python/gjk.cc
src/narrowphase/gjk.cpp
src/narrowphase/narrowphase.cpp
test/gjk.cpp
test/gjk_convergence_criterion.cpp

Multiple little GJK/EPA modifications:
- [API change] Renamed default convergence criterion from `VDB` to `Default`
- Renamed exit status of GJK (no API change, only used internally)
- Removed useless function I previously introduced in EPA
- If EPA encounters badly conditioned problems, do not return nans. Often, the `Degenerate`, `NonConvex` and `InvalidHull` cases, the estimate of the normal and penetration depth is not the best but it's better than returning nans.

Misc gjk epa

---

.github/workflows/ros_ci.yml

Since Noble isn't released yet, there are some hickups. Turning off prerelease should work around it for now.

[CI] Turn off ROS2 Rolling to avoid failure

---

.github/workflows/macos-linux-pip.yml

Hi,
github runners "macos-latest" are now arm64 machines, and the previous build system for darwin arm was not able to generate python 3.8 builds.
Let's deactivate that for now, until I get some time to publish builds for those.

ci pip: no py 3.8 on macos arm64 for now

---

include/hpp/fcl/collision_data.h
include/hpp/fcl/contact_patch.h
src/contact_patch.cpp
src/contact_patch_func_matrix.cpp

In the future, we might want to compute bvh and fields contact patch in a more satisfying way. For now this PR simply removes the throw due to BVH-BVH, BVH-Shape, Hfield-Shape contact patches.

Contact patch: add bvh and hfield

---

CHANGELOG.md
package.xml

This ensures that we have a consistent ABI between this package that uses octomap, and anything else in the system that might use it.  We'll eventually be remove the octomap that we currently have vendored within ROS itself so we can ensure this.
This was enabled by the merging of https://github.com/ros/rosdistro/pull/41623

Switch to the system dependency for octomap.

---

.github/workflows/ros_ci.yml
CHANGELOG.md
INSTALL
include/hpp/fcl/fwd.hh
include/hpp/fcl/internal/traversal_node_setup.h
include/hpp/fcl/serialization/fwd.h
src/narrowphase/support_functions.cpp
test/collision.cpp
test/normal_and_nearest_points.cpp
test/serialization.cpp

Seems like quite a few slipped through in #601. May need another iteration or so after this one.

Address more warnings

---

CHANGELOG.md
test/serialization.cpp

Don't run test on hpp::fcl::Convex without Qhull.
This should fix the ROS CI build.

Fix serialization unit test when running without Qhull support

---

CHANGELOG.md
python/collision-geometries.cc

Solved [#590] by exposing IdVisitor of collision geometries, but it requires eigenpy >=3.7.0

fix issue #590

---

CHANGELOG.md
hpp-fclConfig.cmake
include/hpp/fcl/coal.hpp

Use IMPLIB instead of LOCATION on Windows

Fix hpp-fclConfig.cmake on Windows

---

.github/workflows/macos-linux-pip.yml
.github/workflows/macos-linux-windows-pixi.yml
pixi.lock
pixi.toml

* Replace Python 3.12 by Python 3.13 as the default
* Update pixi.lock
* Test Python 3.13 in CI

Support python 3.13

---

CHANGELOG.md
src/CMakeLists.txt

This will install libcoal.so.3.0.0 and libcoal.so as a symlink, instead of just libcoal.so as a binary.

Fix install version.
